name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { ruby: '2.7', rails: '6.0' }
          - { ruby: '2.7', rails: '6.1' }
          - { ruby: '2.7', rails: '7.0' }
          - { ruby: '3.0', rails: '6.0' }
          - { ruby: '3.0', rails: '6.1' }
          - { ruby: '3.0', rails: '7.0' }
          - { ruby: '3.1', rails: '6.1' }
          - { ruby: '3.1', rails: '7.0' }
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake spec
